import Head from 'next/head'
import { useEffect, useState } from 'react'
import SliderPage from '../components/SliderPage'
import styles from '../styles/Home.module.css'
import { getData } from '../utils/fetchData'
import Product from './product'

// import '~slick-carousel/slick/slick.css'
// import '~slick-carousel/slick/slick-theme.css'
const Home = (props) => {
  const [navBg, setNavBg] = useState(false)
  const changeNavbarColor = () => {
    window.screenY >= 800 ? setNavBg(true) : setNavBg(false)
  }

  useEffect(() => {
    window.addEventListener('scroll', changeNavbarColor)
    return () => {
      window.removeEventListener('scroll', changeNavbarColor)
    }
  }, [])
  console.log(navBg)
  return (
    <div onScroll={changeNavbarColor} className={styles.container}>
      <Head>
        <title>E-commerce_App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <div>
        <main>
          <h1
            style={{ fontSize: 30, color: 'blueviolet', textAlign: 'center' }}
          >
            <div className="">
              <SliderPage />
              <Product product={props.products} />
            </div>
          </h1>
        </main>

        <footer className={styles.footer} style={{ height: '100px' }}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span
              style={{
                paddingLeft: 5,
                color: 'green',
                fontSize: 20,
                fontWeight: 'bold',
              }}
            >
              Khaled Ahasan
            </span>
          </a>
        </footer>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await getData('products')
  return {
    props: {
      products: res.products,
      result: res.result,
    },
  }
}
export default Home
