import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getData } from '../utils/fetchData'
import Product from './product'
const Home = (props) => {
  return (
    <div className={styles.container} >
      <Head>
        <title>E-commerce_App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <h1
            style={{ fontSize: 30, color: 'blueviolet', textAlign: 'center' }}
          >
            <div className=''>
              <Product product={props.products} />
            </div>
          </h1>
        </main>

        <footer className={styles.footer} style={{height:'100px'}}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span
              style={{
                paddingLeft: 5,
                color: 'green',
                fontSize: 20,
                fontWeight: 'bold',
              }}
            >
              Khaled Ahasan
            </span>
          </a>
        </footer>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await getData('products')
  return {
    props: {
      products: res.products,
      result: res.result,
    },
  }
}
export default Home
